- package.json
- src/Poll.tsx
- yarn.lock
The Poll component rerenders its children, even if the content does not change. This leads to a lot of unnecessary render cycles.
This PR fixes that.
> Poll state

- README.md
- package.json
- src/Get.test.tsx
- src/Get.tsx
This pulls in #34 for a new minor release.
> Add debounce

- src/Mutate.tsx
I missed this little return type for the mutate return type during my last PR 😄 
This PR fix this little mistake
> Fix return type

- src/Context.tsx
- src/Get.test.tsx
- src/Get.tsx
- src/Mutate.test.tsx
- src/Mutate.tsx
- src/Poll.test.tsx
- src/Poll.tsx
- src/index.tsx
To provide the best experience ever to deal with errors! 💯 (at least a bit better than before 😅 )
#47
> Feat provider error handling

- src/Get.tsx
- src/Mutate.tsx
- src/index.tsx
Fixes #69 - refer to that for issue description.
> Export method types

- src/Get.test.tsx
- src/Get.tsx
- src/Mutate.tsx
- src/Poll.tsx
> Avoid requests side effects once component unmounts

- src/Mutate.test.tsx
- src/Mutate.tsx
- src/util/composeUrl.test.ts
- src/util/composeUrl.ts
`<Mutate verb="DELETE">{delete => delete("id")}</Mutate>` doesn't work.
> Fix delete with id

- src/Get.test.tsx
- src/Get.tsx
- src/Mutate.test.tsx
- src/Mutate.tsx
- src/Poll.test.tsx
- src/Poll.tsx
Life is just about opportunities 😄 Our dev env was down for 10mn so I found this amazing hole in our error handling management 😅 
I also add `status` in the `error` object to permit an easier error parsing for meaningfull error 💯  
https://github.com/contiamo/restful-react/issues/78
> Better error handling

- src/index.tsx
> exporting missing UseGetProps

- src/scripts/import-open-api.ts
- src/scripts/tests/__snapshots__/import-open-api.test.ts.snap
- src/scripts/tests/import-open-api.test.ts
Another little fix for useGet generator, thanks to @mpotomin integration test.
(should be the last fix 🤞 )
> useGetProps take only 2 generics

- src/Mutate.test.tsx
- src/util/processResponse.ts
Handle the 204 No content response correctly
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
Thanks to @AJHenry 👍
> Handle empty response (204 status)

- src/scripts/import-open-api.ts
- src/scripts/tests/import-open-api.test.ts
And one more edge case found and fixed! 🎉 
Thanks @contiamo/pantheon for this amazing integration test 👍
> Fix generation array of oneOf/allOf case

- src/bin/restful-react-import.ts
If github API responds with an error, we are totally trapped on the flow, this PR add a nice feedback and an easy way to reset the token on bad credentials
> Handle the bad credential case

- src/Get.tsx
This PR is to provide a fix for #136 where the fetch request could throw an error after the component was unmounted
I have not yet been able to create a unit test that consistently reproduces this error as this is a race condition with an error
> Add fix for #136

- src/scripts/import-open-api.ts
- src/scripts/tests/import-open-api.test.ts
I totally forgot to deal with the `nullable` attribute 😅 Until NOWWWWWWWWWW! 🎉 
We ever deal with nullable ref! 😲 (I think we are the only one on internet to do this regarding my previous research on the subject ^^)
> Deal with `nullable` attribute

- src/scripts/import-open-api.ts
- src/scripts/tests/__snapshots__/import-open-api.test.ts.snap
- src/scripts/tests/import-open-api.test.ts
I was testing the docs on our product and I realized that I forgot query params! 😱 
More detail in the diff of the PR (snapshots)
> Add docs to query params

- src/scripts/import-open-api.ts
- src/scripts/tests/import-open-api.test.ts
> #209 Support empty schemas

- yarn.lock
My test npm registry got part of the yarn.lock due global npm config on my side. Sorry about this!
> Update yarn.lock file to use public npm registry

- src/Mutate.tsx
- src/useMutate.test.tsx
- src/useMutate.tsx
> add support for passing queryParams in mutate method

- src/Get.tsx
- src/Mutate.tsx
- src/Poll.tsx
- src/scripts/import-open-api.ts
- src/scripts/tests/__snapshots__/import-open-api.test.ts.snap
- src/scripts/tests/import-open-api.test.ts
- src/useGet.test.tsx
- src/useGet.tsx
- src/useMutate.test.tsx
- src/useMutate.tsx
> feat: add support for path params is useMutate

- README.md
- package.json
- src/Context.tsx
- src/useGet.test.tsx
- src/useGet.tsx
- src/useMutate.test.tsx
- src/useMutate.tsx
> Support queryParamStringifyOptions on RestfulProvider level

- package.json
- src/Context.tsx
- src/Get.test.tsx
- src/Get.tsx
- src/Mutate.tsx
- src/Poll.tsx
- src/bin/restful-react-import.ts
- src/scripts/import-open-api.ts
- src/scripts/tests/__snapshots__/import-open-api.test.ts.snap
- src/scripts/tests/import-open-api.test.ts
- src/useGet.test.tsx
- src/useGet.tsx
- src/useMutate.tsx
- src/util/constructUrl.test.ts
- src/util/constructUrl.tsx
See #289.
@fabien0102 Not certain if this really deserves a minor version bump. Also I reckon I should wrap the body for the DELETE mutation request here (https://github.com/contiamo/restful-react/blob/454db37e029fdd3b8fceb98a6dc977720a91cb0b/src/useMutate.tsx#L134), wasn't too sure about this though, will amend if needed.
> Wrap path parameters with encodeURIComponent

- src/Mutate.tsx
This fix is a continuation of #257 and #168. 
It applies the same changes made on `useMutate` to the `mutate` function.
Without this fix, `Content-Type` is still being filled as `text/plain` when it should be set as `multipart/form-data` by the browser.
This also fixes #264, by not trying to set the default Content-Type if it's already set on `mutateRequestOptions.headers`.
> Support form-data on mutate function (already fixed for useMutate)

- src/useGet.test.tsx
- src/useGet.tsx
- src/useMutate.test.tsx
- src/useMutate.tsx
> Provider resolve call

- src/scripts/import-open-api.ts
- src/scripts/tests/import-open-api.test.ts
Follow-up of #362 (rebasing & adding tests)
> Add support for `anyof`

- package.json
I added React 17 to peer dependencies as per #333 to allow updating.
> Initial support for React 17

- src/scripts/import-open-api.ts
> Fix allOf  in responseBodies generation
