contiamo/restful-react

src/index.tsx
Turns out request methods are case sensitive. Who knew?!
=> Update HTTP verbs in mutations to be uppercase

package.json, src/Get.tsx, src/Mutate.tsx, src/Poll.tsx, yarn.lock
Currently, Restful React has two limitations for our use cases in Contiamo:
- When an error occurs, some errors contain responses in JSON. These responses are now stored in the `error` prop passed to children. Errors are forced into a format detailed below:
```ts
interface Error<S> {
data: S
message: string
}
```
- The `DELETE` verb formerly exposed its API to require a `body`, when really, Restful DELETE requests typically live on `/resource/:resourceId`. Now, the DELETE function takes an ID as an argument instead of an entire object.
=> Fix error handling and resource deletion

src/Get.test.tsx, src/Get.tsx, src/Mutate.tsx, src/Poll.tsx
The following of #17 
I've have removed the throwing inside `fetch`, it was a bit weird and really hard to test. In fact I wondering how it works in real world?
BTW, I think that in this context, it's not really practicle and I prefer to deal with a simple `error` object.
I think that the original idea was to do this:
```jsx
<RestfulProvider base="https://my-awesome-api.fake">
<Get path="">
{(_, {}, { refetch }) => (
<Button
onClick={() => {
refetch()
.then()
.catch();
}}
/>
)}
</Get>
</RestfulProvider>;
```
But it's more natural to deal with error in the first level like this:
```jsx
<RestfulProvider base="https://my-awesome-api.fake">
<Get path="">
{(_, { error }, { refetch }) =>
error ? (
"error!"
) : (
<Button
onClick={() => {
refetch();
}}
/>
)
}
</Get>
</RestfulProvider>;
```
And, …
=> Unit tests - Get component

src/Mutate.test.tsx, src/Mutate.tsx
Actually, if no id is provided for a DELETE operation, we call `${base}${path}/undefined`, so we broken some implementations.
=> Fix Delete action without id

src/Get.tsx, src/Mutate.tsx, src/Poll.tsx, src/index.tsx
We have two differents patterns: `PollProps` vs `GetComponentProps` and we don't export any props for now.
If we want to extend any component, it can be useful to have the props accessible. It's the goal of this PR :wink:
=> Refactor props names and exports

src/Get.tsx, src/Mutate.tsx, src/Poll.tsx, src/util/processResponse.ts
Responses with `Content-Type: application/json; charset: utf-8` are resolved as plain-text responses and cannot be processed accordingly in Restful React.
=> Factor out handling of response content type handler

src/Poll.tsx
=> Add seconds to prefer header

README.md, src/Get.test.tsx, src/Get.tsx
Because it's really cool 😎 , and also because my load-balancer need some vacations ^^
=> Add a debounce option to `Get`

src/Poll.test.tsx, src/Poll.tsx
Our server send us chunk instead of a complete response on long polling (for obvious performance reasons ^^)
The idea is to have `prevData` available in the `Poll:resolve` props, so we can do:
```jsx
<Poll path="" resolve={(data, prevData) => (prevData || "") + data}>
{/* my awesome application */}
</Poll>
```
I also add a lot of unit tests to `Poll` and fix some little behaviour on my way:
-  avoid a useless call on start
- cancel the request on component did mount
=> Add a clean way to consolidate data in `Poll`

src/Poll.test.tsx, src/Poll.tsx
Because as a noob I've commited a `.skip` on this part 😆 and also because we have a lot of foggy spots on this part.
The idea is to be as close as possible of `Get` regarding the comportement and also continue polling after an error (so the `until` props is really useful)
=> Improve the error management for Poll

package.json
I don't think the `engine` setting is right in `package.json` 
It cause built fail in now
```
> warning @canner/restful-react@5.1.1: The engine "vscode" appears to be invalid.
> info fsevents@1.2.4: The platform "linux" is incompatible with this module.
> info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
> warning restful-react@5.2.0: The engine "vscode" appears to be invalid.
> [4/5] Linking dependencies..
```
FYI: https://docs.npmjs.com/files/package.json#engines
=> Remove engine in package.json

src/Get.test.tsx, src/Get.tsx
Actually we don't have the error if we use `<Get wait />`. This PR fix this specific case.
=> Fix the error case on Get with `wait` property

package.json, src/Get.test.tsx, src/Get.tsx, src/Mutate.tsx, src/Poll.test.tsx, src/Poll.tsx
URLs in methods are resolving unexpected, due to the urls are simply concatenating. This PR use `url.resolve` to enable users to use absolute and relative paths expectedly.
=> resolve urls instead concat url strings

src/Context.tsx, src/Get.test.tsx, src/Get.tsx, src/Mutate.test.tsx, src/Mutate.tsx, src/Poll.test.tsx, src/Poll.tsx, src/util/composeUrl.test.ts, src/util/composeUrl.ts
To compose relative urls explicitly using no forward slash in path value. Refer #29 for more background.
If the path starts with forward slash, it is considered as absolute url. If not, it is considered as relative url.
For example,
```
base = "/people" and path = "/absolute" resolves to "/absolute"
```
whereas,
```
base = "/people" and path = "relative" resolves to "/people/relative"
```
In the nested cases, the immediate parent's url becomes base for composition.
For example, 
```
<RestfulProvider base="https://my-awesome-api.fake/MY_SUBROUTE">
<Get path="/absolute-1">
{() => (
<Get path="relative-1">
{() => (
<Get path="/absolute-2">
{() => <Get path="relative-2">{() => <Get path="relative-3">{children}</Get>}</Get>}
</Get>
)}
</Get>
)}
</Get>
</RestfulProvider>
```
emits …
=> compose urls for relative paths cases

.gitignore, example/README.md, example/index.html, example/index.tsx, package.json, src/Get.test.tsx, src/Get.tsx, src/types.ts, src/util/resolveData.ts
This PR fixes #57, adding support for validators that either throw runtime errors or work through a promise, extending the support for libraries like `yup`.
The errors coming from this validation are standard and can produce anything, so they don't fit into the `{ message: string, data: TError | string }` interface - so as a first pass, I am passing a `RESOLVE_ERROR` string as message so it is easily recognizable, and stringifying the actual error inside `data` - which the end user would have to parse back into JSON later. Wonder if there is a better way to deal with this.
=> **Feature:** Add support for validators that are promise-based or throw errors

src/Get.test.tsx, src/Get.tsx
On 6.0.0, we accidentally introduced a regression that rerenders the component infinitely if a `Get` does not have a `resolve` function and the request happens to error. This was introduced by incorrectly comparing resolve functions.
As a way of ensuring function-referential-equivalence, we now stringify the functions to make sure we only rerender when they _actually_ change.
=> Fix an infinite loop on fetching without a resolve function

src/Get.test.tsx, src/Get.tsx, src/Mutate.test.tsx, src/Mutate.tsx, src/util/composeUrl.ts
Currently, the following snippet behaves a little unpredictably. Consider,
```jsx
<RestfulProvider base="https://my-awesome-api.fake/eaegae">
<Get path="/LOL">
{() => (
<Mutate verb="POST" base="https://my-other-api.fake" path="">
{children}
</Mutate>
)}
</Get>
</RestfulProvider>
```
this makes a request to `https://my-other-api.fake/LOL` when the mutate function is called. This is incorrect. It needs to instead, ignore any parent path and defer to `Mutate`'s `path` property (the empty string) _only_, without composing the parent `Get`'s `path` property.
In order for this function to function (pun intended) correctly, the snippet _should_ send a request to `https://my-other-api.fake/`.
This PR fixes this and adds a test case across both `Get` _and_ `Mutate`.
=> Fix base path propagation to ignore parentPath

src/Context.tsx, src/Get.test.tsx, src/Get.tsx, src/Mutate.test.tsx, src/Mutate.tsx, src/Poll.test.tsx, src/Poll.tsx
The idea is to add `response` as extra argument of `onError` to have access to the `url`, `status`, etc for better debugging
=> Add Response in the onError callback

src/Poll.tsx
React should be imported with * because of React.ReactNode is not being exported with React Object I'm using TSX
After installing the package it throws an error React `has no default export`
=> Fix React import on generated d.ts

src/Get.test.tsx, src/Get.tsx
Because it can be cool to refetch when we change the `page` in `queryParams` 😅
=> Fix Get reload on queryParams change

src/Get.test.tsx, src/Get.tsx
We were comparing queryParams for equality and it was always false, leading to infinite rerenders and DDoS attacks.
This PR fixes this.
=> Fix infinite request loop because of queryParam equality

package.json, src/useGet.test.tsx, src/useGet.tsx
The `requestOptions` was not correctly consolidate, this is fixed!
Also I add a bit of sugar to permit the following API:
```ts
const {data, loading, error} = useGet("/");
```
Finally a little fix about react dependency.
This will test on the `@next` release to be sure everything is following in a real project
=> Fix useGet

src/useGet.tsx
A little hotfix on the next version, I forgot `requestOptions` in the dependencies list
=> Add requestOptions in the watch list for refetch

src/Get.test.tsx, src/Poll.test.tsx, src/Poll.tsx
Fixes #112 
I'm not sure this is a proper way, but it works. Get / Poll seem to be quite different and sadly I didn't have much time to dig into the source code.
=> Add support for requestOptions as a method to Poll

src/useGet.test.tsx, src/useGet.tsx
By lazyness, I've choose `url.resolve` composition pattern when I implement the first version of `useGet`, the problem is that it required to add a trailing slash to the `Provider.base` to be able to use the library…
To resolve this, I update a bit the pattern, to permit more convenient url composition, not sure that is yet perfect but it will be test in our internals applications to validate the usage and pattern :wink:
=> Fix useGet url composition pattern

src/bin/restful-react-import.ts
The error when we forget `--output` is really not explicit, let's be more explicit to guide our users 😃
=> Add cli options validators

README.md
`delete` is a reserved keyword in javascript world, let's use something else to have a working example.
=> Avoid to use reserved keyword in the example

src/Mutate.test.tsx, src/Mutate.tsx
The error in `Mutate` was never propagated to the component, we always used `.catch` but it's a legitim usecase and expectation 😅 
Thanks @AJHenry from the reporting 👍 
#121
=> Propagate the error on Mutate

src/scripts/import-open-api.ts, src/scripts/tests/import-open-api.test.ts
Little case forgot during the last refactor, delete route without `id` at the end should be `void`, not `string`
=> Fix delete without id case

src/Mutate.tsx, src/useMutate.tsx
Makes catch case message of the Mutate call and makes it same as for Get
=> **Fix**: unify error format 

.gitignore, src/Mutate.test.tsx, src/Mutate.tsx, src/useMutate.test.tsx, src/useMutate.tsx, tsconfig.json
I need a onMutate callback to unvalidate some cache, the plan is to slowly introduce some caching strategy, not yet sure how we want to this but a `onMutate` callback can be useful for many situation.
For now I just have a `memoize` function around our restful-react getter, and the idea is to unvalidate the cache on every related mutation 😉
=> Add a onMutate callback.

src/useGet.tsx
This change will allow to use `lazy` prop to skip immediate loading of results. We need this because we can't put hooks inside `if`
=> Watch for lazy change in useGet

src/bin/restful-react-import.ts
This PR fixes #154 and also makes the `--output` option optional, printing to standard output in case there is no output specified. This is useful for dry runs and a common pattern for CLI tools (see babel).
=> CLI improvements

src/Context.tsx, src/Get.test.tsx, src/Get.tsx, src/Mutate.test.tsx, src/Mutate.tsx, src/Poll.test.tsx, src/Poll.tsx, src/useGet.test.tsx, src/useGet.tsx, src/useMutate.test.tsx, src/useMutate.tsx
In some cases, we'd like query params to be inherited by all hooks/components under a given provider. This PR makes this possible.
=> Support Global queryparams

src/util/composeUrl.ts
Fixes #159 and partially #93.
Get Component does not resolve the path properly when the base prop is not provided. It returns the path with a preceding slash. 
This is not the case in useGet as useGet uses a different resolvePath function in `useGet.tsx`, while Get component uses `composePath` & `composeUrl`.
Tests: No additional tests were written and all tests are passing.
=> Fix: Path resolution when base path is null/empty

README.md, package.json, yarn.lock
Fixes #93 
Added: Getting started with react native and editable example on the expo. Bumped react version to 16.8.5 from 16.8.4 to match react-dom dependency and added react to dev dependency, so it won't have any usage conflicts
=> Add: Getting started with react native and editable example on expo

src/useGet.tsx
`refetch()` type definition is outdated. Actually, it receives options as its first argument.
https://github.com/contiamo/restful-react/blob/59ccaa2a487ca8844c86a1be7aca65cc7949dcc1/src/useGet.tsx#L221
=> Fix type definition of refetch()

src/scripts/import-open-api.ts, src/scripts/tests/__snapshots__/import-open-api.test.ts.snap, src/scripts/tests/import-open-api.test.ts, src/scripts/tests/petstore-expanded.yaml
Deal with the discriminator pattern to solve #156 
This is definitely not a full specs implementation, we only resolve discriminator inside `components/schemas`.
We can of course iterate later when we/somebody have more advanced needs.
=> Deal with discriminator pattern

src/Context.tsx
Add capabilities to display the name of the Provider and the Consumer as per #107
=> feat: set RestfulProviderContext as displayName for Context component

README.md, src/Context.tsx, src/Get.test.tsx, src/Get.tsx, src/Mutate.tsx, src/Poll.test.tsx, src/Poll.tsx, src/useGet.tsx, src/useMutate.tsx
Second go at allowing for promised request options to be provided to components and hooks.
See #180 for more detail
=> Promise request options

src/scripts/import-open-api.ts, src/scripts/tests/__snapshots__/import-open-api.test.ts.snap, src/scripts/tests/import-open-api.test.ts
Expose `summary` and `description` in the generated components/types from open-api specs
Fix #184
=> Use `summary` and `description` as generated documentation

src/scripts/import-open-api.ts, src/scripts/tests/__snapshots__/import-open-api.test.ts.snap, src/scripts/tests/petstore-expanded.yaml
Fixes #177 
As per the OpenApi spec, `requestBody` inside the `Operation` object may be a reference. Previously restful-react was not generating types for this case.
I added a new endpoint to the extended petstore yaml that exhibits this behavior for testing.
=> Support requestBody fields that are reference objects

src/scripts/import-open-api.ts
This fix allows us to use generated useDelete or delete react component even the route has a trailing slash (my_route/${id}/).
Generated route for using delete components works only when the route has no trailing slash (my_route/${id}).
=> Route fix for generated 'delete' components from openapi

.eslintrc.js, .gitignore, .prettierrc, package.json, rollup.config.js, src/Get.test.tsx, src/Mutate.test.tsx, src/Poll.test.tsx, src/bin/restful-react-import.ts, src/scripts/import-open-api.ts, src/scripts/tests/import-open-api.test.ts, src/useGet.test.tsx, src/useMutate.test.tsx, src/useMutate.tsx, src/util/useDeepCompareEffect.ts, tsconfig.json, yarn.lock
Our project is not compiled to umd, and I saw this package mentionned somewhere in our issues ^^ (and as a curious person, I had to give a try 😁)
@weyert I would like to have your feedback on this one, since you tried the "manual" version in #212 
- I had to fix all the tests types since I increase the typesafety.
- I still have a custom rollup for the scripts due to https://github.com/jaredpalmer/tsdx/issues/338
=> Migrate to Tsdx

src/bin/restful-react-import.ts, src/scripts/import-open-api.ts, src/scripts/tests/import-open-api.test.ts
Inline types are hard to consume (and probably break with documentation ^^) so let's export them correctly for `RequestBody`
#225
=> Generate a separate type for `RequestBody`

README.md, examples/fetchers.ts, examples/restful-react.config.js, src/bin/restful-react-import.ts, src/scripts/import-open-api.ts, src/scripts/tests/import-open-api.test.ts
To bring a bit of flexibility on the openAPI generator, I would like to introduce a new `customGenerator` for advanced configurations.
This is in response for #226 and #223, I tried a first integration in our product with some `fetch` generator, this works quite well 😃 
I could come with something more easy to use and restrictive, but I want to give a try for more customization. Indeed, everybody project is a bit different (axios, basic fetch, rxjs…) so let's the user come with what he need!
You can have a preview of this PR in `restful-react@canary`
```ts
// restful-react.config.js
customImport: `import { getConfig } from "../../products/IdP/Config"\nimport { customGet, customMutate, CustomGetProps, CustomMutateProps } from "../fetchers"`,
customGenerator: ({ componentName, verb, route, …
```
=> Custom generator

src/scripts/import-open-api.ts, src/scripts/tests/import-open-api.test.ts
#231
We didn't deal with more advanced content type, this should be way more flexible.
=> Deal with charset

package.json, src/bin/restful-react-import.ts
After 1 year of resetting my token at every `npm install`, this is time to fix my initial mistake 😁 
Let's store the github token in home, like everybody, it's a token user so it should go in a user scope, not project.
=> Save token in home instead of node_modules

src/scripts/import-open-api.ts, src/scripts/tests/__snapshots__/import-open-api.test.ts.snap, src/scripts/tests/petstore-expanded.yaml
For the following object
```yml
Request:
properties:
actions:
type: array
items:
type: string
enum:
- create
- view
- update
- delete
```
produces
```ts
interface Request {
actions: 'create' | 'view' | 'update' | 'delete''[]
}
```
but expected result is
```ts
interface Request {
actions: ('create' | 'view' | 'update' | 'delete'')[]
}
```
=> fix: codegen for array of enums

README.md, src/Context.tsx, src/Get.test.tsx, src/Get.tsx, src/Mutate.test.tsx, src/Mutate.tsx, src/Poll.test.tsx, src/Poll.tsx, src/useGet.test.tsx, src/useGet.tsx, src/useMutate.test.tsx, src/useMutate.tsx
I have a problem with handling some global actions with request and response to handle refresh token on authentication cycle, for example I need to check on every request if the access token is expired or not and replace the Authorization header value with refresh token instead of the access token and on the response of this request I need to get the new access token and save it globally.
Added two new triggers **onRequest**, **onResponse** like **onError** trigger and added call for these triggers when initializing the request and when get a new response on all library components and hooks.
- handle any staff needed to be handled globally depend on request or response objects.
- listen to all requests and responses globally for debugging and logging purposes.
- I guess this PR has a …
=> Added onRequest & onResponse in RestfulProvider

src/useMutate.tsx
Allows you to pass FormData objects to useMutate. 
Example:
```javascript
const formData = new FormData()
formData.append('image', file)
const response = await mutate(formData)
```
fixes #168
=> Support FormData

src/Get.test.tsx, src/Poll.test.tsx, src/util/processResponse.ts
- if the content-type is "application/json" or "text/plain" behavior will not change.
- all other cases will return whole response object.
See: https://github.com/contiamo/restful-react/issues/261
=> #261 - processResponse support blob & Co

src/scripts/import-open-api.ts, src/scripts/tests/import-open-api.test.ts
I encountered a problem where the openapi spec had a nullable type defined as
```
oneOf:
- $ref: 'someRef'
- type: null
```
This was translated into ```SomeRef | any```  because the type "null" was not supported explicitly as a scalar type
=> Openapi null type

README.md, src/scripts/import-open-api.ts, src/scripts/tests/__snapshots__/import-open-api.test.ts.snap, src/scripts/tests/import-open-api.test.ts, src/useGet.test.tsx, src/useGet.tsx, src/useMutate.test.tsx, src/useMutate.tsx
Add `mock` props in `useGet` and `useMutate` to provide an easy way to mock an api call (with type-safety)
More information in the `README.md` of this PR
=> Add mocks support

src/Mutate.test.tsx, src/useMutate.test.tsx, src/useMutate.tsx
Resolves #288 
This is fully backward compatible for body of type string/number. So, this PR adds supports for body as `FormData` or `Object` which is useful for some cases.
Nice, that it's already like this in Mutate component. Only the hook has missed this point. 
p.s somehow we need to avoid duplicating code/tests in the component and hook (If you have the same feeling, let me know, I will open a new issue to discuss in more details). Probably, I don't fully understand the idea of having two sources of truth (Component and Hook) instead of one (Hook).
So, my idea is to use hook in the component directly. So, all logic will be in one place (Hook).
Just an example:
```jsx
function Mutate({ children, ...mutateProps }) {
const { mutate, loading, error, absolutePath } = …
```
=> Handle body object for DELETE request

README.md, src/Context.tsx, src/Get.tsx, src/Mutate.tsx, src/Poll.tsx, src/useGet.test.tsx, src/useGet.tsx, src/useMutate.tsx
In some usecases, we would like add new values into request header which are depend on the request content.
For example, we tried to implement authentication method [oauth-dpop](https://tools.ietf.org/html/draft-ietf-oauth-dpop-01), but we found we don't have enough information in function requestOptions (request's url, method)
The original function:
```ts
() => Partial<RequestInit>
```
I modified this function like this:
```ts
(url: string, method: string, requestBody?: string) => Partial<RequestInit>)
```
So that we can achieve our purpose.
```ts
<RestfulProvider
base="String!"
resolve={data => data}
requestOptions={async (url, method) => {
// generate JWT with request's url and method.
const dpopProofJWT = await DPoP(keypair, 'ES256', url, method);
return { headers: { DPoP: …
```
=> Add params in function requestOptions

README.md, package.json, src/scripts/import-open-api.ts
Nothing special, it just fixes typo in readme based on this PR https://github.com/contiamo/restful-react/pull/274
=> Fix README: rename mocks prop to mock

src/Get.tsx, src/useGet.test.tsx, src/useGet.tsx
Having some stale data after error is really confusing and causing some issues.
We also don't have any good use cases in mind where having the previous data can be useful, so let's simplify the library behaviour.
=> Clear the `data` after an error

.github/workflows/npm-publish.yaml, package.json, yarn.lock
An old version of `auto-changelog` was there and didn't support the `--starting-version` flag
=> Fix GitHub release

src/useMutate.test.tsx, src/useMutate.tsx
Hopefully begins to address #186
Approach:
* Remove (mutable) references to state. Instead, hook into the
(immutable) `setState` function in the mutate function body where
state references are necessary
* Try very hard to be honest about what dependencies may change in the
dependency array, but leave only immutable dependencies that depend only
on props (almost totally successful)
Hopefully addresses some of #186 , at least with respect to the mutate function.
=> Stabilize the identity of the mutate function

src/useGet.test.tsx, src/useGet.tsx, src/util/useDeepCompareEffect.ts
Stabilizing the identity of the `fetchData` function presents some
challenges. The biggest is that `fetchData` needs to have access to
`state` and `setState`, but it needs to have the most up-to-date version
of them in order to work. There are two ways to have done this: the
first is to move the definition of `fetchData` into the function body of
`useGet` itself and make it a closure over the `state` and `setState`
variables - that is the approach taken here. Alternatively, we could
define `fetchData` as a function which takes `state` and `setState` as
parameters, but is closed over a particular combination of props and
context values - this option wasn't explored.
The end result is that the identity of the `refetch` function is stable
given a certain set of props and context, and it is …
=> stabilize the identity of useGet and its refetch method

src/useMutate.test.tsx, src/useMutate.tsx, src/util/useDeepCompareEffect.ts
Revisiting #335 in light of the issue noted in #337
Stabilize the useMutate function even more by using a deep
compare effect. This better handles cases in which the argument to
`useMutate` is an inline object, which is the typical use case.
=> Stabilize use mutate even more

src/scripts/import-open-api.ts, src/scripts/tests/import-open-api.test.ts
Currently if you generate types based on the following definition, `age_range` is typed as `number[]`
```yaml
age_range:
description: 'A range of passenger ages (start and end, inclusively)'
type: array
items:
type: number
minItems: 2
maxItems: 2
```
As the array should only contain two items, it would be nice if it was typed as `[number, number]`
This will conflict with #362, but if you support the idea, I'll rebase afterwards
=> Add support for tuples

src/scripts/import-open-api.ts, src/scripts/tests/import-open-api.test.ts
Given the following spec
```yaml
description: A representation of a floor of a bus.
title: Floor
type: object
properties:
level:
description: The floor number.
enum:
- 1
- 2
type: number
```
I would like the type to be generated as 
```ts
interface Floor {
level: 1 | 2;
}
```
Additional question: I don't use React but this is the best library I found to generate type from OpenAPI specs, is there a plan to split this library into type generation & react related stuff?
=> support enum on type number

src/scripts/import-open-api.ts, src/scripts/tests/__snapshots__/import-open-api.test.ts.snap
Resolves #366 (see issue for motivation).
Adds all path parameters to generated interfaces for DELETE requests when `--skipReact` is set.
=> Keep last path parameter when skipping React

src/scripts/import-open-api.ts, src/scripts/tests/import-open-api.test.ts
https://github.com/contiamo/restful-react/pull/364 introduced an issue with empty `required` lists: invalid types are generated in that case, e.g. `Require<Foo & Bar, >`.
=> Fix: empty required should not generate invalid types.
